#!/usr/bin/env bash

builtin cd "$HOME"

# Set your DIARY_DIR in bashrc. Else it goes into ~/Documents/diary.
[[ -z "$DIARY_DIR" ]] && DIARY_DIR="$HOME/Documents/diary"

EDITOR="${EDITOR:-vim}"

mkdir -p "$DIARY_DIR" && builtin cd "$DIARY_DIR"

# Get current date
year=$(date +%Y)
month=$(date +%m)

mkdir -p "$year"/"$month" && builtin cd "$year"/"$month"

# Create diary files in the appropriate places and opens them.
datename=$(date +%F)
[[ ! -f "$datename.md" ]] && echo "# $datename, $(date +%A)" >> "$datename.md"
echo "## $(date +%H:%M:%S)" >> "$datename.md"

"$EDITOR" "$datename.md"
